export default function Privacy(){return <main className="section"><div className="container" style={{maxWidth:950}}><div className="card"><h1>Politique de confidentialité — Alerte Citoyen</h1><p className="muted">Version de travail — Côte d'Ivoire — mise à jour le 23 août 2026</p>
<p><b>Important :</b> ce document est une base de conformité et doit être vérifié par un juriste ivoirien avant mise en production. Il est conçu en cohérence avec la loi ivoirienne n°2013-450 du 19 juin 2013 relative à la protection des données à caractère personnel et avec les exigences de l'autorité compétente. Les formalités administratives et autorisations nécessaires doivent être vérifiées avant tout traitement.</p>
<h2>1. Responsable du traitement</h2><p>Le responsable du traitement est l'entité ou la personne juridique qui exploite Alerte Citoyen. Les mentions définitives (raison sociale, adresse, email de contact, numéro d'identification et coordonnées du responsable de la protection des données lorsqu'il est requis) seront renseignées avant le lancement public.</p>
<h2>2. Finalités</h2><p>Alerte Citoyen traite des données afin de créer et gérer les comptes, publier et rechercher des alertes, faciliter l'entraide, modérer les contenus, prévenir la fraude et les abus, assurer la sécurité du service, gérer les récompenses lorsqu'elles sont activées et respecter les obligations légales applicables.</p>
<h2>3. Principes de traitement</h2><p>Les données sont traitées de manière licite et loyale, pour des finalités déterminées, avec une information claire et selon un principe de minimisation. La plateforme doit éviter de collecter ou d'afficher des informations qui ne sont pas nécessaires à l'objectif de l'alerte.</p>
<h2>4. Données pouvant être traitées</h2><p>Selon le service utilisé : nom, email, numéro de téléphone facultatif, informations de compte, contenu d'alerte, localisation approximative, fichiers envoyés, informations techniques, journaux de sécurité et informations nécessaires à une récompense ou à un paiement. Les données sensibles font l'objet d'une protection renforcée et ne doivent pas être publiées sans nécessité et base légale appropriée.</p>
<h2>5. Alertes, anonymat et personnes disparues</h2><p>L'anonymat d'affichage peut masquer l'identité d'un contributeur au public, mais ne constitue pas une promesse d'anonymat absolu vis-à-vis des obligations légales. Pour les personnes disparues, notamment les mineurs et personnes vulnérables, Alerte Citoyen applique une politique de minimisation renforcée : pas d'adresse privée, pas de coordonnées exactes ou de documents sensibles en accès public lorsque leur divulgation crée un risque.</p>
<h2>6. Base juridique et consentement</h2><p>Lorsque le consentement est requis, il doit être libre, spécifique, éclairé et non ambigu. Lorsque la loi permet une autre base juridique, celle-ci doit être documentée. Les traitements liés à la sécurité, à une obligation légale ou à la sauvegarde des droits et libertés doivent être appréciés au cas par cas.</p>
<h2>7. Destinataires et sous-traitants</h2><p>Les données peuvent être confiées à des prestataires techniques nécessaires au fonctionnement du service (hébergement, base de données, email, stockage sécurisé, paiement). Ces prestataires doivent présenter des garanties suffisantes de confidentialité et de sécurité. Les données ne sont pas vendues à des fins publicitaires.</p>
<h2>8. Transferts hors de Côte d'Ivoire</h2><p>Certains prestataires cloud peuvent traiter des données depuis d'autres pays. Avant mise en production, Alerte Citoyen doit documenter les pays concernés, les garanties applicables et les formalités éventuellement nécessaires auprès de l'autorité compétente.</p>
<h2>9. Sécurité</h2><p>La plateforme met en œuvre des mesures techniques et organisationnelles adaptées : HTTPS, mots de passe hachés, sessions sécurisées, contrôle d'accès par rôles, limitation de débit, journalisation, sauvegardes, séparation des données privées et publiques, protection des fichiers et procédure de réponse aux incidents. Aucun système ne peut garantir un risque zéro.</p>
<h2>10. Conservation</h2><p>Les données sont conservées pendant la durée nécessaire aux finalités prévues, puis supprimées ou anonymisées lorsque leur conservation n'est plus justifiée, sous réserve des obligations légales et de la nécessité de conserver certaines traces de sécurité ou de preuve.</p>
<h2>11. Droits des personnes</h2><p>Conformément au cadre ivoirien applicable, les personnes disposent des droits prévus par la loi, notamment selon les conditions applicables : information, accès, rectification et, lorsque prévu, opposition, suppression ou autres droits. Les demandes doivent être adressées au contact officiel publié par l'éditeur.</p>
<h2>12. Cookies</h2><p>Les cookies strictement nécessaires peuvent être utilisés pour les sessions et la sécurité. Les cookies non essentiels, s'ils sont ajoutés ultérieurement, doivent être soumis aux règles d'information et de consentement applicables.</p>
<h2>13. Mineurs et personnes vulnérables</h2><p>Les contenus concernant les mineurs ou personnes vulnérables font l'objet de contrôles renforcés. La plateforme peut masquer ou retirer une publication lorsqu'elle présente un risque pour la personne concernée.</p>
<h2>14. Récompenses et conversion en argent</h2><p>Le solde affiché dans l'espace utilisateur représente une fonctionnalité de récompense et ne constitue pas automatiquement un compte bancaire ou de monnaie électronique. Toute conversion en FCFA doit passer par un prestataire autorisé lorsque la réglementation l'exige, avec vérifications anti-fraude et, le cas échéant, obligations d'identification.</p>
<h2>15. Violations de données</h2><p>Un dispositif interne de détection, de documentation et de notification des incidents doit être maintenu. En cas d'incident affectant des données personnelles, l'éditeur suit les obligations et délais imposés par le droit applicable et par l'autorité compétente.</p>
<h2>16. Contact et réclamations</h2><p>Un email officiel de confidentialité doit être publié avant le lancement. Les utilisateurs peuvent également utiliser les mécanismes de plainte ou de recours prévus par la réglementation ivoirienne.</p>
<h2>17. Modification</h2><p>La présente politique peut être mise à jour pour refléter les évolutions du service ou de la réglementation. La date de dernière mise à jour est affichée en haut de la page.</p>
<div className="notice"><b>Référence juridique :</b> loi ivoirienne n°2013-450 du 19 juin 2013 relative à la protection des données à caractère personnel. La conformité finale doit être validée avant déploiement.</div>
</div></div></main>}
